### ISSUE TITLE
Error compiling the Create Branch

### ISSUE THREAD

**Issue by thannemann** [wizbrewery/wiz-Open-ArdBir#1]
`./opt/arduino-builder/arduino-builder -compile -core-api-version 10611 -build-path /tmp/809896488/build -hardware opt/arduino-builder/hardware -hardware ./opt/cores -tools opt/arduino-builder/tools -tools ./opt/tools -built-in-libraries opt/libraries/latest -libraries /tmp/809896488/pinned -libraries /tmp/809896488/custom -fqbn arduino:avr:mega:cpu=atmega2560 -build-cache /tmp -logger humantags -verbose=false /tmp/809896488/Open-ArdBir2

Multiple libraries were found for "DallasTemperature.h"

Used: /home/admin/builder/opt/libraries/latest/dallastemperature-3-7-6

Not used: /home/admin/builder/opt/libraries/latest/max31850-dallastemp-1-0-0

Multiple libraries were found for "EEPROM.h"

Used: /home/admin/builder/opt/cores/arduino/avr/libraries/EEPROM

Not used: /home/admin/builder/opt/libraries/latest/arduino-nvm-0-9-1

Multiple libraries were found for "LiquidCrystal_I2C.h"

Used: /home/admin/builder/opt/libraries/latest/jm_liquidcrystal_i2c-1-0-0

Not used: /home/admin/builder/opt/libraries/latest/liquidcrystal-i2c-1-1-2

Multiple libraries were found for "OneWire.h"

Used: /home/admin/builder/opt/libraries/latest/onewire-2-3-3

Not used: /home/admin/builder/opt/libraries/latest/max31850-onewire-1-0-1

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::available()'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/home/admin/builder/opt/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld: Disabling relaxation: it will not work with multiple definitions

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::rxBufferLength'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::rxBufferIndex'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::read()'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::rxBuffer'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::peek()'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::flush()'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::onReceiveService(unsigned char*, int)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::user_onReceive'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::onRequestService()'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::user_onRequest'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::txBufferIndex'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::txBufferLength'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::write(unsigned char const*, unsigned int)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::transmitting'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::write(unsigned char)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::txBuffer'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::TwoWire()'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::TwoWire()'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `Wire'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::begin()'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::begin(unsigned char)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::begin(int)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::end()'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::setClock(unsigned long)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::beginTransmission(unsigned char)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::txAddress'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::beginTransmission(int)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::endTransmission(unsigned char)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::requestFrom(unsigned char, unsigned char, unsigned long, unsigned char, unsigned char)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::requestFrom(unsigned char, unsigned char, unsigned char)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::requestFrom(unsigned char, unsigned char)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::requestFrom(int, int)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::requestFrom(int, int, int)'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::endTransmission()'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::onReceive(void (*)(int))'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/jm_Wire.cpp.o (symbol from plugin): In function `TwoWire::available()':

(.text+0x0): multiple definition of `TwoWire::onRequest(void (*)())'

/tmp/809896488/build/libraries/Wire/Wire.cpp.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_readFrom'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_writeTo'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_transmit'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_init'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_disable'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_setAddress'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_setFrequency'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_attachSlaveRxEvent'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_attachSlaveTxEvent'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_reply'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_stop'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `twi_releaseBus'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

/tmp/809896488/build/libraries/jm_wire-1-0-1/utility/jm_twi.c.o (symbol from plugin): In function `twi_readFrom':

(.text+0x0): multiple definition of `__vector_39'

/tmp/809896488/build/libraries/Wire/utility/twi.c.o (symbol from plugin):(.text+0x0): first defined here

collect2: error: ld returned 1 exit status

exit status 1`

**Comment by wizbrewery** [comment]
Hi thannemann,  not familiar with the web ide s,  seems to be a lot of duplicate library errors in the code above!  Anyhow I've uploaded the latest t branch wiz2.  I checked by downloading zip and making sure it compiled.  With the web ide maybe the built in libraries are referenced different?  Can you get hold of the arduino ide to try? regards  Waldy

**Comment by thannemann** [comment]
Thanks Waldy it seems that the web ide which they called "create" has issues with multiple libraries of the same name.  I will check in the current desktop version later today, and let you know how it works

Todd
